guardian:
 # joint_blw_velocity_controller:
   # type: effort_controllers/JointEffortController #type: velocity_controllers/JointVelocityController
   # joint: joint_back_left_wheel
   # pid: {p: 100.0, i: 0.01, d: 20.0}
 # joint_brw_velocity_controller:
   # type: effort_controllers/JointEffortController
   # joint: joint_back_right_wheel
   # pid: {p: 100.0, i: 0.01, d: 20.0}
 # joint_frw_velocity_controller:
   # type: effort_controllers/JointEffortController
   # joint: joint_front_right_wheel
   # pid: {p: 100.0, i: 0.01, d: 20.0}
 # joint_flw_velocity_controller:
   # type: effort_controllers/JointEffortController
   # joint: joint_front_left_wheel
   # pid: {p: 100.0, i: 0.01, d: 20.0}

 # joint_pan_position_controller:
   # type: effort_controllers/JointPositionController
   # joint: joint_camera_pan
   # pid: {p: 100.0, i: 0.01, d: 50.0}

 # joint_tilt_position_controller:
   # type: effort_controllers/JointPositionController
   # joint: joint_camera_tilt
   # pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_tilt_laser_position_controller:
    type: effort_controllers/JointPositionController
    joint: hokuyo_tilt_laser_joint
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_read_state_controller: # Publishes the joint states of all the joints with hardware_interfaces and advertises the topic on /joint_states. 
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
