schunk_powerball:

  j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_2_joint
    pid: {p: 100.0, i: 1.0, d: 10.0}

  j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_3_joint
    pid: {p: 100.0, i: 1.0, d: 10.0}

  j4_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j5_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j6_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}    

  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
